title: Akshay Nalawade
logo: /assets/img/image.png
description: 
  <br>
  Hi, I'm Akshay Nalawade, a Data driven professional currently pursuing Master's degree in Data Analytics and Visualization from The Katz School at Yeshiva University, New York. 
  I aim to develop and implement data-driven solutions to cater complex business problems. 
  In my previous roles as Data Analyst, I played a key role in transforming complex datasets into meaningful reports that drove strategic decision-making. 
  I believe I have good working knowledge of various data technologies like Python, SQL, R, Power-BI, Spark and AWS. 
  I bring not only technical skills but also strong interpersonal and collaborative abilities, essential for successfully implementing data-driven solutions.
  <br>
  
  <a href="assets/img/Akshay_Nalawade.pdf>Resume</a>
  <a href="https://www.linkedin.com/in/nalawadeakshay/">LinkedIn</a>
  <a href="https://github.com/Akshay710/">Github</a>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
