title: Akshay Nalawade
logo: /assets/img/image.png
description: 
  <br>
  - Hi, I'm Akshay Nalawade, a Data driven professional currently pursuing Master's degree in Data Analytics and Visualization from The Katz School at Yeshiva University, New York.
  - Proeficient with various data technologies like Python, SQL, R, Power-BI, Excel, Spark and AWS. 
  
  <br>
  
  <a href="assets/img/Akshay_Nalawade.pdf>Resume</a>
  <a href="https://www.linkedin.com/in/nalawadeakshay/">LinkedIn</a>
  <a href="https://github.com/Akshay710/">Github</a>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
