title: <p align="center"> Akshay Nalawade </p>
logo: /assets/img/image.png
description: 

 <br>
 Hi, I'm Akshay, a Data driven professional, proficient with various data technologies like Python, SQL, R, Power-BI, Excel, Spark and AWS. 
 Seeking opportunities to facilitate Data-Driven Decision making. Let's unlock the power of your data!
 
 
 <br>
 </p>


  <a href="assets/img/Akshay_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nalawadeakshay/">LinkedIn</a> |
  <a href="https://github.com/Akshay710/">Github</a>
