title: <p align="center"> Akshay Nalawade </p>
logo: /assets/img/image.png
description: 

 <br>
 Hi, I'm Akshay, a Data driven professional currently pursuing Master's degree in Data Analytics and Visualization 
 from The Katz School at Yeshiva University, New York.             
      Proeficient with various data technologies like Python, SQL, R, Power-BI, Excel, Spark and AWS. 
 
 
 <br>
 </p>


  <a href="assets/img/Akshay_Nalawade.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nalawadeakshay/">LinkedIn</a> |
  <a href="https://github.com/Akshay710/">Github</a>
